id: AF1B15878
title: 'Schøyen Collection: Brāhmī, published'
type: translation
pechas:
- I4FF972EF
source_metadata:
  languages:
  - sa
  datatype: PlainText
  created_at: 2023-02-08 16:16:46.552815
  last_modified_at: 2023-02-08 16:16:46.552826
alignment_to_base:
  I4FF972EF/983B: 5B4A
